"""Crash-safe approval and recovery primitives for EviForge."""

from mewcode.recovery.canonical import (
    MISSING_FILE_HASH,
    bytes_sha256,
    canonical_json_hash,
    canonical_realpath,
    file_sha256,
)
from mewcode.recovery.models import (
    ActionRecord,
    ActionState,
    ApprovalTicket,
    AttemptLease,
    BindingMismatchError,
    Checkpoint,
    ConcurrentReservationError,
    EffectKind,
    FencingConflictError,
    InvalidActionTransition,
    JournalEntry,
    PreconditionsFailedError,
    RecoveryItem,
    RecoveryReport,
    SimulatedCrash,
    TicketState,
    TicketUnavailableError,
    UncertainActionError,
)
from mewcode.recovery.store import RecoveryStore
from mewcode.recovery.coordinator import JournalHandle, RecoveryExecutionCoordinator

__all__ = [
    "ActionRecord",
    "ActionState",
    "ApprovalTicket",
    "AttemptLease",
    "BindingMismatchError",
    "Checkpoint",
    "ConcurrentReservationError",
    "EffectKind",
    "FencingConflictError",
    "InvalidActionTransition",
    "JournalEntry",
    "MISSING_FILE_HASH",
    "PreconditionsFailedError",
    "RecoveryItem",
    "RecoveryReport",
    "RecoveryStore",
    "JournalHandle",
    "RecoveryExecutionCoordinator",
    "SimulatedCrash",
    "TicketState",
    "TicketUnavailableError",
    "UncertainActionError",
    "bytes_sha256",
    "canonical_json_hash",
    "canonical_realpath",
    "file_sha256",
]
